In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset= pd.read_csv('Social_Network_Ads.csv')
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       0   19            19000          0
1    15810944       0   35            20000          0
2    15668575       1   26            43000          0
3    15603246       1   27            57000          0
4    15804002       0   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       1   46            41000          1
396  15706071       0   51            23000          1
397  15654296       1   50            20000          1
398  15755018       0   36            33000          0
399  15594041       1   49            36000          1

[400 rows x 5 columns]

In [2]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, 4].values
X

array([[    0,    19, 19000],
       [    0,    35, 20000],
       [    1,    26, 43000],
       ...,
       [    1,    50, 20000],
       [    0,    36, 33000],
       [    1,    49, 36000]], dtype=int64)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
print(X_train)

[[     0     58 144000]
 [     1     59  83000]
 [     1     24  55000]
 [     1     26  35000]
 [     1     58  38000]
 [     1     42  80000]
 [     1     40  75000]
 [     0     59 130000]
 [     1     46  41000]
 [     1     41  60000]
 [     0     42  64000]
 [     1     37 146000]
 [     1     23  48000]
 [     0     25  33000]
 [     0     24  84000]
 [     1     27  96000]
 [     0     23  63000]
 [     0     48  33000]
 [     0     48  90000]
 [     0     42 104000]
 [     1     44  39000]
 [     0     32 120000]
 [     1     38  50000]
 [     1     32 135000]
 [     1     52  21000]
 [     1     53 104000]
 [     0     39  42000]
 [     0     38  61000]
 [     1     36  50000]
 [     1     36  63000]
 [     1     35  25000]
 [     0     35  50000]
 [     0     42  73000]
 [     1     47  49000]
 [     1     59  29000]
 [     0     49  65000]
 [     1     45 131000]
 [     1     31  89000]
 [     1     46  82000]
 [     1     47  51000]
 [     0     26  15000]
 [     0     60 

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

[[-1.02532046e+00  1.92295008e+00  2.14601566e+00]
 [ 9.75304830e-01  2.02016082e+00  3.78719297e-01]
 [ 9.75304830e-01 -1.38221530e+00 -4.32498705e-01]
 [ 9.75304830e-01 -1.18779381e+00 -1.01194013e+00]
 [ 9.75304830e-01  1.92295008e+00 -9.25023920e-01]
 [ 9.75304830e-01  3.67578135e-01  2.91803083e-01]
 [ 9.75304830e-01  1.73156642e-01  1.46942725e-01]
 [-1.02532046e+00  2.02016082e+00  1.74040666e+00]
 [ 9.75304830e-01  7.56421121e-01 -8.38107706e-01]
 [ 9.75304830e-01  2.70367388e-01 -2.87638347e-01]
 [-1.02532046e+00  3.67578135e-01 -1.71750061e-01]
 [ 9.75304830e-01 -1.18475597e-01  2.20395980e+00]
 [ 9.75304830e-01 -1.47942605e+00 -6.35303205e-01]
 [-1.02532046e+00 -1.28500455e+00 -1.06988428e+00]
 [-1.02532046e+00 -1.38221530e+00  4.07691369e-01]
 [ 9.75304830e-01 -1.09058306e+00  7.55356227e-01]
 [-1.02532046e+00 -1.47942605e+00 -2.00722133e-01]
 [-1.02532046e+00  9.50842613e-01 -1.06988428e+00]
 [-1.02532046e+00  9.50842613e-01  5.81523798e-01]
 [-1.02532046e+00  3.67578135e-

In [7]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1], dtype=int64)

In [8]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[54  4]
 [ 4 18]]


In [9]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))
print('Error: %.2f' % ((1-accuracy_score(y_test, y_pred))*100))

Accuracy: 90.00
Error: 10.00


In [10]:
from sklearn.ensemble import RandomForestClassifier
rfmodel = RandomForestClassifier(n_estimators = 20, criterion ='entropy', random_state = 0)
rfmodel.fit(X_train, y_train) 
rf_pred = rfmodel.predict(X_test)
rf_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1], dtype=int64)

In [11]:
from sklearn.metrics import confusion_matrix
cmc = confusion_matrix(y_test, rf_pred)
print('Confusion matrix: ')
print(cmc)

Confusion matrix: 
[[54  4]
 [ 3 19]]


In [12]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, rf_pred)*100))
print('Error: %.2f' % ((1-accuracy_score(y_test, rf_pred))*100))

Accuracy: 91.25
Error: 8.75
